workflows:
  ios-workflow:
    name: iOS Workflow with Remote Access
    environment:
      xcode: latest
    scripts:
      - name: Enable Remote Access
        script: |
          #!/bin/bash
          # This will enable remote access for 60 minutes
          codemagic remote-access --duration 60
      - name: Wait for manual project setup
        script: |
          echo "Remote access enabled. Please connect via VNC using the credentials above."
          echo "After setting up the Xcode project, you can commit it directly from the VM."
          echo "Waiting for remote session to complete..."
          sleep 3000 # 50 minutes timeout
    artifacts:
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log
      - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.app
      - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.dSYM 
