workflows:
  ios-workflow:
    name: iOS Finance Manager Workflow
    instance_type: mac_mini_m2
    max_build_duration: 120
    inputs:
      xcode_version:
        description: Xcode version to use
        type: choice
        options: ["latest", "16.3", "16.2", "16.1", "16.0", "15.4"]
        default: latest
      submit_to_testflight:
        description: Submit build to TestFlight
        type: boolean
        default: false
      distribution_type:
        description: iOS distribution type
        type: choice
        options: ["app_store", "ad_hoc", "development"]
        default: development
    integrations:
      # Replace with your App Store Connect API key name after setting it up in Codemagic UI
      app_store_connect: app_store_connect_api_key_name
    environment:
      ios_signing:
        distribution_type: ${{ inputs.distribution_type }}
        # Bundle identifier must match your Apple Developer Portal registration
        bundle_identifier: io.codemagic.financemanager
      vars:
        BUNDLE_ID: "io.codemagic.financemanager"
        XCODE_PROJECT: "FinanceManager.xcodeproj" # Update this if your project name is different
        XCODE_SCHEME: "FinanceManagerApp" # Update this if your scheme name is different
      xcode: ${{ inputs.xcode_version }}
      cocoapods: default
    cache:
      cache_paths:
        - $HOME/Library/Caches/CocoaPods
        - $HOME/.gradle/caches
    scripts:
      - name: Install CocoaPods dependencies
        script: |
          pod install || true
      - name: Set up code signing
        script: |
          # Initialize keychain
          keychain initialize
          
          # For development or ad-hoc distribution
          if [ "${{ inputs.distribution_type }}" = "development" ] || [ "${{ inputs.distribution_type }}" = "ad_hoc" ]; then
            # Create development certificate and provisioning profile
            app-store-connect fetch-signing-files "$BUNDLE_ID" \
              --type ${{ inputs.distribution_type == 'ad_hoc' && 'IOS_APP_ADHOC' || 'IOS_APP_DEVELOPMENT' }} \
              --create
          else
            # Create app store distribution certificate and profile
            app-store-connect fetch-signing-files "$BUNDLE_ID" \
              --type IOS_APP_STORE \
              --create
          fi
          
          # Add certificates to keychain
          keychain add-certificates
          
          # Set up code signing settings
          xcode-project use-profiles
      - name: Build iOS app
        script: |
          xcode-project build-ipa \
            --project "$XCODE_PROJECT" \
            --scheme "$XCODE_SCHEME" \
            --configuration Release
    artifacts:
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log
      - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.app
      - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.dSYM
    publishing:
      app_store_connect:
        auth: integration
        submit_to_testflight: ${{ inputs.submit_to_testflight }}
      email:
        recipients:
          - your-email@example.com
        notify:
          success: true
          failure: true
          
  # New workflow for simulator builds (no code signing required)
  ios-simulator:
    name: iOS Simulator Build
    instance_type: mac_mini_m2
    max_build_duration: 60
    environment:
      vars:
        XCODE_PROJECT: "FinanceManager.xcodeproj" # Update this if your project name is different
        XCODE_SCHEME: "FinanceManagerApp" # Update this if your scheme name is different
      xcode: latest
      cocoapods: default
    cache:
      cache_paths:
        - $HOME/Library/Caches/CocoaPods
    scripts:
      - name: Install CocoaPods dependencies
        script: |
          pod install || true
      - name: Build for iOS simulator
        script: |
          xcodebuild build \
            -project "$XCODE_PROJECT" \
            -scheme "$XCODE_SCHEME" \
            -sdk iphonesimulator \
            -configuration Debug \
            CODE_SIGN_IDENTITY="" \
            CODE_SIGNING_REQUIRED=NO \
            CODE_SIGNING_ALLOWED=NO
    artifacts:
      - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.app
      - /tmp/xcodebuild_logs/*.log
    publishing:
      email:
        recipients:
          - your-email@example.com
        notify:
          success: true
          failure: true 
