workflows:
  ios-diagnostic:
    name: iOS Build Diagnostic
    instance_type: mac_mini_m2
    environment:
      xcode: latest
    scripts:
      - name: System information
        script: |
          echo "===== SYSTEM INFO ====="
          uname -a
          echo "\nXcode version:"
          xcodebuild -version
          echo "\nSwift version:"
          swift --version
          echo "\nSDK paths:"
          xcrun --sdk iphoneos --show-sdk-path
          
      - name: Repository contents
        script: |
          echo "===== REPOSITORY CONTENTS ====="
          echo "Current directory:"
          pwd
          echo "\nRepository root contents:"
          ls -la
          
          echo "\nAvailable Swift files:"
          find . -name "*.swift" | sort
          
          echo "\nDirectory structure:"
          find . -type d | sort
          
          echo "\nXcode project files (if any):"
          find . -name "*.xcodeproj" -o -name "*.pbxproj" -o -name "*.xcworkspace"
          
      - name: Simple Swift test
        script: |
          echo "===== SWIFT TEST ====="
          # Create a directory for our test
          mkdir -p swifttest
          cd swifttest
          
          # Create a simple Swift file
          echo 'print("Hello, world!")' > hello.swift
          
          # Try to compile (macOS target first - should work on any Mac)
          echo "\nCompiling for macOS:"
          swiftc hello.swift -o hello_macos
          
          # Show the result
          echo "\nCompilation results:"
          ls -la
