   workflows:
     ios-build:
       name: iOS Build
       instance_type: mac_mini_m1
       environment:
         xcode: latest
       scripts:
         - name: Build iOS app
           script: xcodebuild build -project "FinanceManager.xcodeproj" -scheme "FinanceManager" -sdk iphonesimulator
       artifacts:
         - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.app
