workflows:
  ios-native:
    name: iOS Native App
    instance_type: mac_mini_m2
    environment:
      xcode: latest
      cocoapods: default
    scripts:
      - name: Set up code signing
        script: |
          echo "Setting up code signing"
      - name: Install CocoaPods dependencies
        script: |
          find . -name "Podfile" -execdir pod install \;
      - name: Build iOS app
        script: |
          xcodebuild clean build -workspace "*.xcworkspace" -scheme "FinanceManager" -configuration Debug -sdk iphoneos CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO CODE_SIGNING_ALLOWED=NO
    artifacts:
      - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.app
