workflows:
  ios-native:
    name: iOS Native App
    instance_type: mac_mini_m2
    environment:
      xcode: latest
      cocoapods: default
    scripts:
      - name: Debug project structure
        script: |
          echo "Current directory:"
          pwd
          echo "Repository contents:"
          ls -la
          echo "Looking for Xcode project files:"
          find . -name "*.xcodeproj"
          echo "Looking for workspace files:"
          find . -name "*.xcworkspace"
          echo "Looking for Swift files:"
          find . -name "*.swift"
          
      - name: Prepare Xcode project
        script: |
          # Create a simple directory for Swift files if needed
          mkdir -p FinanceManagerApp
          
          # Copy Swift files to the directory
          find . -name "*.swift" -exec cp {} FinanceManagerApp/ \;
          
          cd FinanceManagerApp
          
          # Use Swift Package Manager to create a basic project
          swift package init --type executable
          swift package generate-xcodeproj
          
      - name: Build iOS app
        script: |
          # List available projects
          find . -name "*.xcodeproj"
          
          # Try to build the created project
          cd FinanceManagerApp
          XCODEPROJ=$(find . -name "*.xcodeproj" | head -n 1)
          if [ -n "$XCODEPROJ" ]; then
            echo "Found Xcode project: $XCODEPROJ"
            PROJECT_NAME=$(basename "$XCODEPROJ" .xcodeproj)
            xcodebuild -project "$XCODEPROJ" -scheme "$PROJECT_NAME" -configuration Debug -sdk iphoneos CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO CODE_SIGNING_ALLOWED=NO
          else
            echo "No .xcodeproj found. Build cannot continue."
            exit 1
          fi
    artifacts:
      - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.app
      - FinanceManagerApp/build/**/*.app
