workflows:
  ios-workflow:
    name: iOS Finance Manager Workflow
    instance_type: mac_mini_m2
    max_build_duration: 120
    inputs:
      xcode_version:
        description: Xcode version to use
        type: choice
        options: ["latest", "16.3", "16.2", "16.1", "16.0", "15.4"]
        default: latest
      submit_to_testflight:
        description: Submit build to TestFlight
        type: boolean
        default: false
      distribution_type:
        description: iOS distribution type
        type: choice
        options: ["app_store", "ad_hoc", "development"]
        default: development
    integrations:
      # Replace with your App Store Connect API key name after setting it up in Codemagic UI
      app_store_connect: app_store_connect_api_key_name
    environment:
      ios_signing:
        distribution_type: ${{ inputs.distribution_type }}
        # Bundle identifier must match your Apple Developer Portal registration
        bundle_identifier: io.codemagic.financemanager
      vars:
        BUNDLE_ID: "io.codemagic.financemanager"
        XCODE_PROJECT: "FinanceManager.xcodeproj" # Update this if your project name is different
        XCODE_SCHEME: "FinanceManagerApp" # Update this if your scheme name is different
      xcode: ${{ inputs.xcode_version }}
      cocoapods: default
    cache:
      cache_paths:
        - $HOME/Library/Caches/CocoaPods
        - $HOME/.gradle/caches
    scripts:
      - name: Install CocoaPods dependencies
        script: |
          pod install || true
      - name: Set up code signing
        script: |
          # Initialize keychain
          keychain initialize
          
          # For development or ad-hoc distribution
          if [ "${{ inputs.distribution_type }}" = "development" ] || [ "${{ inputs.distribution_type }}" = "ad_hoc" ]; then
            # Create development certificate and provisioning profile
            app-store-connect fetch-signing-files "$BUNDLE_ID" \
              --type ${{ inputs.distribution_type == 'ad_hoc' && 'IOS_APP_ADHOC' || 'IOS_APP_DEVELOPMENT' }} \
              --create
          else
            # Create app store distribution certificate and profile
            app-store-connect fetch-signing-files "$BUNDLE_ID" \
              --type IOS_APP_STORE \
              --create
          fi
          
          # Add certificates to keychain
          keychain add-certificates
          
          # Set up code signing settings
          xcode-project use-profiles
      - name: Build iOS app
        script: |
          xcode-project build-ipa \
            --project "$XCODE_PROJECT" \
            --scheme "$XCODE_SCHEME" \
            --configuration Release
    artifacts:
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log
      - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.app
      - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.dSYM
    publishing:
      app_store_connect:
        auth: integration
        submit_to_testflight: ${{ inputs.submit_to_testflight }}
      email:
        recipients:
          - your-email@example.com
        notify:
          success: true
          failure: true
          
  # Updated workflow for SwiftPM-based projects without Xcode project file
  ios-simulator:
    name: iOS Simulator Build
    instance_type: mac_mini_m2
    max_build_duration: 60
    environment:
      vars:
        APP_NAME: "FinanceManagerApp"
        BUNDLE_ID: "io.codemagic.financemanager"
      xcode: latest
    scripts:
      - name: List project structure
        script: |
          echo "Project structure:"
          find . -type f -name "*.swift" | sort
      
      - name: Create Swift Package
        script: |
          # Create a basic Package.swift file if none exists
          if [ ! -f "Package.swift" ]; then
            echo "Creating Package.swift file..."
            cat > Package.swift << EOL
// swift-tools-version:5.5
import PackageDescription

let package = Package(
    name: "FinanceManagerApp",
    platforms: [.iOS(.v15)],
    products: [
        .executable(name: "FinanceManagerApp", targets: ["FinanceManagerApp"]),
    ],
    targets: [
        .executableTarget(
            name: "FinanceManagerApp",
            path: "."
        )
    ]
)
EOL
          fi
      
      - name: Create Xcode project
        script: |
          # Generate Xcode project from Swift Package
          swift package generate-xcodeproj
          
          # Validate project creation
          ls -la
          
      - name: Build for iOS simulator
        script: |
          # Set simulator destination
          DESTINATION="platform=iOS Simulator,name=iPhone 14,OS=latest"
          
          # Build with Xcode
          xcodebuild build \
            -project "${APP_NAME}.xcodeproj" \
            -scheme "${APP_NAME}" \
            -destination "${DESTINATION}" \
            -configuration Debug \
            CODE_SIGN_IDENTITY="" \
            CODE_SIGNING_REQUIRED=NO \
            CODE_SIGNING_ALLOWED=NO \
            ONLY_ACTIVE_ARCH=YES
    artifacts:
      - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.app
      - /tmp/xcodebuild_logs/*.log
    publishing:
      email:
        recipients:
          - your-email@example.com
        notify:
          success: true
          failure: true 
