workflows:
  ios-native:
    name: iOS Native App
    instance_type: mac_mini_m2
    environment:
      xcode: latest
      cocoapods: default
    scripts:
      - name: Debug project structure
        script: |
          echo "Current directory:"
          pwd
          echo "Repository contents:"
          ls -la
          echo "Looking for Xcode project files:"
          find . -name "*.xcodeproj"
          echo "Looking for workspace files:"
          find . -name "*.xcworkspace"
          echo "Looking for Swift files:"
          find . -name "*.swift"
          
      - name: Create basic Xcode project
        script: |
          # Create a basic Xcode project without trying to change directories
          mkdir -p FinanceManagerProject
          cd FinanceManagerProject
          swift package init --type executable
          swift package generate-xcodeproj
          
      - name: Build iOS app
        script: |
          # Find any Xcode projects in current directory or subdirectories
          XCODEPROJ=$(find . -name "*.xcodeproj" | head -n 1)
          
          if [ -n "$XCODEPROJ" ]; then
            echo "Found Xcode project: $XCODEPROJ"
            PROJECT_DIR=$(dirname "$XCODEPROJ")
            cd "$PROJECT_DIR"
            PROJECT_NAME=$(basename "$XCODEPROJ" .xcodeproj)
            
            # List available schemes
            echo "Available schemes:"
            xcodebuild -project "$XCODEPROJ" -list
            
            # Try to build
            xcodebuild -project "$(basename "$XCODEPROJ")" -scheme "$PROJECT_NAME" -configuration Debug -sdk iphoneos CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO CODE_SIGNING_ALLOWED=NO
          else
            echo "No .xcodeproj found. Build cannot continue."
            exit 1
          fi
    artifacts:
      - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.app
      - build/**/*.app
      - FinanceManagerProject/build/**/*.app
